### ISSUE TITLE
How to up- or download a file

### ISSUE THREAD

**Issue by klemensl** [NAVPERF/NAVLoadTest#20]
Hi,
we are trying to load test our NAV 2015 Application, but in order to do this we have to download files, change their content, and upload them again (otherwise our use case is not fullfilled). Does NAVLoadTest support this in any ways or are there other/better tools/frameworks to accomplish this requirement?

thx, klemensl

**Comment by freddydk** [comment]
For downloading I have used code like this:

                    var excelAction = analysesPage.Action("Create New Document");
                    var uri = userContext.RoleCenterPage.Session.CatchUriToShow(() => excelAction.Invoke());
                    using (var webClient = new WebClient())
                    {
                        webClient.Credentials = new NetworkCredential("User1", "P@ssword123");
                        var content = webClient.DownloadData(uri);
                        File.WriteAllBytes("c:\temp\test.xlsx", content);
                    }
                    TestScenario.ClosePage(TestContext, userContext, analysesPage);

As you can see, you catch a URL, which you then need to stream down to the Client.
I seem to remember, that there was a bug which was fixed in NAV 2016 doing this – I am investigating whether this bug is fixed in NAV 2015.

For upload, I don’t think that there is support for that currently. In order to simulate this, I created a function in a new codeunit on the server, from which I downloaded the document (turned around).
Not sure whether you can use the same mechanism. Alternatively you could send the document to a web service or a codeunit.

/Freddy

**Comment by klemensl** [comment]
Hi Freddy,
thx for your super fast reply! I will try your download solution and also investigate your suggestions for  upload a file.

thx, klemensl

**Comment by garglalit** [comment]
Please tell me how to load test NAV 2013 which have windows client.
From various froums it come to know that it can be tested with Application Toolset(.fob) as well as with Visual Studio.

Please guide for windows client
What type and level of programing skills required for this.

**Comment by wortho** [comment]
Hi Gargalit,
The NAVLoadTest toolkit does not support testing via the WindowsClient.
NAVLoadTest uses the WebClient (actually the ClientService) to execute logical UI actions on the server. By running the WebClient locally and not on the NavServer you can simulate the load that a Windows Client would place on the server. 

Regards,

David
